// WARNING: do not edit this file directly
//          the content is auto-generated.

import { lazy } from 'solid-js'
import type { RouteDefinition } from '@solidjs/router'

export const GeneratedRoutes = [
  {
    path: ["/"],
    component: lazy(() => import("@/routes/layout.tsx")),
    children: [
      {
        path: ["/"],
        children: [
          {
            path: ["membership"],
            component: lazy(() => import("@/routes/(home)/page.tsx")),
          },
        ],
      },
    ],
  },
] satisfies RouteDefinition[];
