// WARNING: do not edit this file directly
//          the content is auto-generated.

import { lazy } from 'solid-js'
import type { RouteDefinition } from '@solidjs/router'

export const GeneratedRoutes = [
  {
    path: ["/"],
    component: lazy(() => import("../../routes/(index)/page.tsx"))
  },
] satisfies RouteDefinition[]